### PR TITLE
Updated composer.json and tests to comply with Symfony 2.1 and FOSUserBundle master

### PR DESCRIPTION
**Pull request by kolah**
I've updated composer.json and tests to comply with Symfony 2.1 and most recent FOSUserBundle version.

I hope these changes would be useful.

### CODE REVIEW

**Comment by leopro** [comment]
Thank you ;)
Now I'm on holidays when I will come back I'll merge the PR unless my partner already did it.

Thanks a lot

Il giorno 02/lug/2012, alle ore 15:47, Krzysztof Kolasiakreply@reply.github.com ha scritto:

**Comment by kolah** [comment]
It still needs some checking, but I'm going to test it in one of my recent projects. Have a nice holidays :)

**Comment by kolah** [comment]
@Sydney-o9 Do you still have any validation issues? For me it's working fine

**Comment by Sydney-o9** [comment]
No validation issues. Works like a charm :-)

**Comment by kolah** [comment]
There is one important validation issue - in UserDiscriminator in methods `getRegistrationForm()` and `getProfileForm()` have hardcoded validation groups, which is bad when you want to use custom validation against forms.

**Comment by Sydney-o9** [comment]
Thanks kolah. 
Guys, I know I shouldn't ask this question here, but quickly: "Do you know if we can implement FOSFacebookBundle" with NmnMultiUserBundle? I am just wondering if this wouldn't be a problem to choose the class of the user upon login?? 
If no, maybe this is something that would be worth implementing in master? Any thoughts on this? :-)

**Comment by Sydney-o9** [comment]
Hi Leonardo/Kolah, I just retested the bundle, and there still is a major problem. 

Try doing this:
1/ register one UserOneType
2/ register one UserTwoType
3/ edit the profile of UserOneType with the username of UserTwoType.

SQLSTATE[23000]: Integrity constraint violation.

Validation does not work.
Do you have any ideas what the problem is?

**Comment by kolah** [comment]
This is not bundle problem - it's caused by UniqueEntity validator constraint, which ignoges base class. I can provide sample validator which has targetClass option.

**Comment by Sydney-o9** [comment]
That would be great! How can we do this? Could you give me some hints on how to do this? Thanks Kolah, you're awesome. I spent like 5 hours...on this!

**Comment by kolah** [comment]
Here's how I did it:
https://gist.github.com/3205664

You will need to use custom validation group for your base class, to override FOSUserBundle default ones.

``` yaml
Acme\UserBundle\Entity\UserBase:
    constraints:
        - Acme\DemoBundle\Validator\Constraints\UniqueEntity:
            fields: usernameCanonical
            errorPath: username
            message: The username is already used
            groups: [ AcmeRegistration, AcmeProfile ]
            targetClass: Acme\UserBundle\Entity\UserBase
        - Acme\DemoBundle\Validator\Constraints\UniqueEntity:
            fields: emailCanonical
            errorPath: email
            message: The email is already used
            groups: [ AcmeRegistration, AcmeProfile ]
            targetClass: Acme\UserBundle\Entity\UserBase
```

**Comment by Sydney-o9** [comment]
Kolah, you're a legend! Works amazingly well :-) There is no way I could find this myself. Well done!

**Pull request merged**
